### ISSUE TITLE
Hex file breaks code

### ISSUE THREAD

**Issue by colbro51** [Salamek/picpro#2]
Hi
Working from scratch and using the information provided in this pdf:

http://www.romstore.ru/system/storage/download/30557g%20-PIC12C5XX-PIC12C5XXA-PIC12CE5XX.pdf

we see the addresses to use for config flags and customer ID code:

Page 4: address 0FFF for config; page 5: customer ID code at addreses 0200-0203
See also code protection table on page 9.

However when I construct a hex data file with just the configuration fuses and the termination line
and attempt to verify them, the program fails (as below).

```
colin@linuxmint201:~/pic$ cat /home/colin/pic/fuses.hex
:020FFF00FF0FE2
:00000001FF
colin@linuxmint201:~/pic$ python3 picPgmr.py
********************************************************************************
picpro verify -p /dev/ttyUSB0 -i /home/colin/pic/fuses.hex -t 12C508A
--------------------------------------------------------------------------------
Waiting for user to insert chip into socket with pin 1 at socket pin 13
Chip detected.
Traceback (most recent call last):
  File "/home/colin/.local/bin/picpro", line 8, in <module>
    sys.exit(main())
  File "/home/colin/.local/lib/python3.8/site-packages/picpro/bin/picpro.py", line 434, in main
    getattr(command, 'chosen')()  # Execute the function specified by the user.
  File "/home/colin/.local/lib/python3.8/site-packages/picpro/bin/picpro.py", line 111, in verify
    program_pic(
  File "/home/colin/.local/lib/python3.8/site-packages/picpro/bin/picpro.py", line 365, in program_pic
    rom_data, eeprom_data, id_data, fuse_values = prepare_flash_data_from_hex_file(chip_info, hex_file, pic_id, fuses)
  File "/home/colin/.local/lib/python3.8/site-packages/picpro/bin/picpro.py", line 253, in prepare_flash_data_from_hex_file
    raise ValueError('ROM record starts on odd address.')
ValueError: ROM record starts on odd address.
================================================================================
```

Since I do not have access to any 'proper' hex files (my asm, dasm, sim code from decades ago was all written in python)
I am at a loss to know what I should be coding in the hex file.

Also when I tried to verify fifteen ROM words of 0FFF against a new blank chip the verification failed?
:0803F000FF0FFF0FFF0FFF0FCD
:0603F800FF0FFF0FFF0FD5
:00000001FF

At lastly, how do I read the ID and fuse settings after programming?

Thanks, Colin

**Comment by Salamek** [comment]
@colbro51 well i tested this project only with "full fat" HEX files, since it uses custom parser that ~expect all chips supported areas to be provided in hex file, no wonder it crashes... 
I'm using `sdcc` to build my HEX file from C code or `gpasm` to build ASM to HEX file...

What do you trying to achieve exactly?

And reading ID an fuse values is not implemented in CLI interface, but there is a function for it in `ProtocolInterface.read_config`

**Comment by colbro51** [comment]
Thanks, I guess at this stage I am simply after an example "full fat" HEX file for a pic12c508a.  From that I can figure out the addressing expected for the ID and fuses. Since they are simple text files if you could paste even a blank sample that would help.
I do not actually need the verification option for the rom as I can use the read option to do my own code verification.

**Comment by Salamek** [comment]
I have only 12F675 in here... (12C508A is kinda deprecated)

**Comment by colbro51** [comment]
I have a large number of these old chips and have a simulator and use for them, hence my choice. In the past I used P16PRO with a parallel port programming module but cannot port to my current PC. I do have some hex output that it output but the address for the ID and fuses do not match the programming specs:
[ https://microchipdeveloper.com/ipe:sqtp-hex-file-format ]  <--- Intel hex format
P16PRO:
:0804000003000A0005000700DB   <---  ID 3A57 at 0400...
:021FFE00EA0FE8                            <---  Fuses at 1FFE
Specs:
http://www.romstore.ru/system/storage/download/30557g%20-PIC12C5XX-PIC12C5XXA-PIC12CE5XX.pdf
Page 4: address 0FFF for config      <--- Fuses at 0FFF
Page 5: customer ID code at addresses 0200-0203  <--- ID at 0200  
See also code protection table on page 9.
I guess I might try the microchip forum to see if I can get this sorted.
Thanks
Colin

**Comment by colbro51** [comment]
I just had an aha moment!  My confusion lies with interpretation of what the addressing refers to.  In the case of intel hex code the addresses refer to bytes whereas for the chips the addresses refer to words (effectively 2*bytes).  Therefore the information above corresponds directly.
2 * 0x0200  -->  0x0400     and   2 * 0x0FFF  -->  0x1FFE
Sometimes one just needs to sleep on it (and picpro complaining about me giving it an odd address in a hex file).
Appreciate your work.
Cheers
Colin

**Comment by Salamek** [comment]
@colbro51 i'm glad you figured it out (OT: it also helps me to sleep on it, or take a shit lol)
