### ISSUE TITLE
Unable to open serial port "/dev/ttyUSB0".

### ISSUE THREAD

**Issue by KinTsume** [Salamek/picpro#7]
I'm having this error while trying to execute any command. Any ideas on how to fix that?

"Unable to open serial port "/dev/ttyUSB0".
Be sure port identifier is valid and that you have access to it."

**Comment by Salamek** [comment]
Well did you check that `/dev/ttyUSB0` exists and that you have access to it from your current user? (On some distros you need to be in correct group to access tty* or just run as root)
